language: bash
services: docker

env:
  - DIR=master
  - DIR=1.9 VARIANT=alpine
  - DIR=1.8 VARIANT=alpine

before_script:
  - eval $(awk '/ELIXIR_VERSION=/ { sub(/@/, "-", $2); print $2; exit }' ${DIR}/${VARIANT}/Dockerfile)
  - image="elixir:${ELIXIR_VERSION#v}${VARIANT:+-$VARIANT}"

script:
  - docker build --pull -t "$image" "${DIR}/${VARIANT}"

after_script:
  - docker images
