general-config: &general-config
  parallelism: 1
  docker:
    - image: circleci/circleci-cli

version: 2

jobs:
  build-master:
    <<: *general-config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: docker build --pull -t elixir:master-alpine master
      - run:
          name: Show images
          command: docker images
  build-1.8:
    <<: *general-config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: docker build --pull -t elixir:1.8-alpine 1.8/alpine
      - run:
          name: Show images
          command: docker images
  build-1.9:
    <<: *general-config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: docker build --pull -t elixir:1.9-alpine 1.9/alpine
      - run:
          name: Show images
          command: docker images

workflows:
  version: 2
  full_test_suite:
    jobs:
      - build-master
      - build-1.8
      - build-1.9
